server:
  port: 0

spring:
  application:
    name: spring-cloud-stream-kafka-stream
  jackson:
    default-property-inclusion: non_empty
    deserialization:
      fail-on-unknown-properties: false
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cloud:
    function:
      definition: ourBinding
    stream:
      bindings:
        ourBinding-in-0:
          destination: item-a
        ourBinding-in-1:
          destination: item-b
        ourBinding-out-0:
          destination: item-c
      kafka:
        streams:
#          https://cloud.spring.io/spring-cloud-stream-binder-kafka/multi/multi__kafka_streams_binder.html
#          doc non a jour sur serdeError ( depreciee )
          binder:
            applicationId: our-app-id
            brokers: localhost:9092
            auto-create-topics: true
            consumerProperties:
              specific.avro.reader: true
              schema.registry.url: http://localhost:8081
              auto.register.schemas: true
              key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
              value.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
              spring.deserializer.value.delegate.class: io.confluent.kafka.serializers.JsonSerializer
            producerProperties:
              specific.avro.reader: true
              schema.registry.url: http://localhost:8081
              auto.register.schemas: true
              key.serializer: org.apache.kafka.common.serialization.StringSerializer
              value.serializer: io.confluent.kafka.serializers.JsonSerializer
          default:
            consumer:
              valueSerde: org.apache.kafka.common.serialization.Serdes$StringSerde
              startOffset: earliest
              dlqName: our-dlq
          bindings:
            ourBinding-in-0:
              consumer:
                materialized-as: store-item-a
                deserialization-exception-handler: sendtodlq
            ourBinding-in-1:
              consumer:
                materialized-as: store-item-b
                deserialization-exception-handler: sendtodlq


